# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Researchers
    url: researchers
    weight: 10
  - name: Publications
    url: publication
    weight: 20
  - name: Projects
    url: project
    weight: 30
 - name: IDEALAB
    url: idealab
    weight: 40
  - name: Lab Work
    url: lab-work
    weight: 50
  - name: Walking Lab
    url: walking-lab
    weight: 60
  - name: Events
    url: event
    weight: 70
  - name: Contact
    url: contact
    weight: 80
